<a href="https://colab.research.google.com/github/AsmaaKhamis1911/Deep-Learning-With-PyTorch/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch

In [2]:
import numpy as np

In [3]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [4]:
mynp=np.random.rand(3,3)
mynp

array([[0.19509059, 0.99664203, 0.0655583 ],
       [0.54492739, 0.86874571, 0.80487341],
       [0.69867865, 0.46233868, 0.30786067]])

In [8]:
mytensor=torch.randn(3)
mytensor


tensor([ 0.0439, -0.2394, -0.7848])

In [9]:
mytensor2=torch.zeros(3,3)
mytensor2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
mytensor3=torch.tensor(mynp)
mytensor3

tensor([[0.1951, 0.9966, 0.0656],
        [0.5449, 0.8687, 0.8049],
        [0.6987, 0.4623, 0.3079]], dtype=torch.float64)