<a href="https://colab.research.google.com/github/AsmaaKhamis1911/Deep-Learning-With-PyTorch/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [2]:
import numpy as np

In [3]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [4]:
mynp=np.random.rand(3,3)
mynp

array([[0.19509059, 0.99664203, 0.0655583 ],
       [0.54492739, 0.86874571, 0.80487341],
       [0.69867865, 0.46233868, 0.30786067]])

In [8]:
mytensor=torch.randn(3)
mytensor


tensor([ 0.0439, -0.2394, -0.7848])

In [9]:
mytensor2=torch.zeros(3,3)
mytensor2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
mytensor3=torch.tensor(mynp)
mytensor3

tensor([[0.1951, 0.9966, 0.0656],
        [0.5449, 0.8687, 0.8049],
        [0.6987, 0.4623, 0.3079]], dtype=torch.float64)

In [3]:
mytorch=torch.arange(3)
mytorch

tensor([0, 1, 2])

In [5]:
mytorch=mytorch.reshape(3,1)
mytorch

tensor([[0],
        [1],
        [2]])

In [6]:
mytorch2=torch.arange(3)
mytorch2

tensor([0, 1, 2])

In [9]:
mytorch2=mytorch2.reshape(3,-1)
mytorch2

tensor([[0],
        [1],
        [2]])

In [10]:
mytorch3=torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
mytorch4=mytorch3.view(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
mytorch5=torch.arange(10)
mytorch5


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
mytorch5[3]

tensor(3)

In [17]:
mytorch6=mytorch5.reshape(2,5)
mytorch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
mytorch5[3]=0
mytorch5

tensor([0, 1, 2, 0, 4, 5, 6, 7, 8, 9])

In [19]:
mytorch6

tensor([[0, 1, 2, 0, 4],
        [5, 6, 7, 8, 9]])

In [20]:
mytorch7=torch.arange(10)
mytorch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
mytorch8=mytorch7.reshape(5,2)
mytorch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
mytorch8[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
mytorch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])